#!/bin/sh
if ( test -r r.$NUMBER -a ! -r c.$NUMBER ) then
	CONSTANTS=r
	BIFURCATION=p
	SOLUTIONS=q
else
	CONSTANTS=c
	BIFURCATION=b
	SOLUTIONS=s
fi
cp $BIFURCATION.$1  $BIFURCATION.$2
cp $SOLUTIONS.$1  $SOLUTIONS.$2
cp d.$1  d.$2
cp $CONSTANTS.$1  $CONSTANTS.$2
echo "Copying $BIFURCATION.$1 to $BIFURCATION.$2 ... done"
echo "Copying $SOLUTIONS.$1 to $SOLUTIONS.$2 ... done"
echo "Copying d.$1 to d.$2 ... done"
echo "Copying $CONSTANTS.$1 to $CONSTANTS.$2 ... done"
