#!/bin/sh
if ( test $# -ge 1 ) then
	if ( test -r b.$1 ) then
		BIFURCATION=b
		SOLUTIONS=s
	else
		BIFURCATION=p
		SOLUTIONS=q
	fi
fi
if ( test $# -eq 1 ) then
	cp $BIFURCATION.$1 fort.27
	cp $SOLUTIONS.$1 fort.28
	$AUTO_DIR/bin/autlab
	rm fort.27
        rm fort.28
        if (test -r fort.37) then
		cp $BIFURCATION.$1 $BIFURCATION.$1~
		mv fort.37 $BIFURCATION.$1 
        fi
        if (test -r fort.38) then
		cp $SOLUTIONS.$1 $SOLUTIONS.$1~
		mv fort.38 $SOLUTIONS.$1 
		echo " Rewriting finished."
        fi
elif( test $# -eq 2 ) then
	cp $BIFURCATION.$1 fort.27
	cp $SOLUTIONS.$1 fort.28
	$AUTO_DIR/bin/autlab
	rm fort.27
        rm fort.28
        if (test -r fort.37) then
		mv fort.37 $BIFURCATION.$2 
        fi
        if (test -r fort.38) then
		mv fort.38 $SOLUTIONS.$2 
		echo " Rewriting finished."
        fi
else
	cp fort.7 fort.27
        cp fort.8 fort.28
	$AUTO_DIR/bin/autlab
	rm fort.27
        rm fort.28
        if (test -r fort.37) then
		cp fort.7 fort.7~
		mv fort.37 fort.7
        fi
        if (test -r fort.38) then
		cp fort.8 fort.8~
		mv fort.38 fort.8
		echo " Rewriting finished."
        fi
fi
