#!/bin/sh
if ( test -r r.$NUMBER -a ! -r c.$NUMBER ) then
	CONSTANTS=r
	BIFURCATION=p
	SOLUTIONS=q
else
	CONSTANTS=c
	BIFURCATION=b
	SOLUTIONS=s
fi
mv -f $BIFURCATION.$1  $BIFURCATION.$2
mv -f $SOLUTIONS.$1  $SOLUTIONS.$2
mv -f d.$1  d.$2
mv -f $CONSTANTS.$1  $CONSTANTS.$2
echo "Renaming $BIFURCATION.$1 as $BIFURCATION.$2 ... done"
echo "Renaming $SOLUTIONS.$1 as $SOLUTIONS.$2 ... done"
echo "Renaming d.$1 as d.$2 ... done"
echo "Renaming $CONSTANTS.$1 as $CONSTANTS.$2 ... done"
